### PR TITLE
fix: extension build with pnpm is missing node_modules

### LINKED ISSUE #296: `pnpm build` is not including external dependency in .cdix file
This is an error introduced during migration to pnpm. `pnpm install` acts differently when executed in module subfolder and node_modules with requested dependency is not created. That leads to publishing extension nightly build that fails to activate when installed in podman desktop.

### PR DESCRIPTION
**Pull request by dgolovin**
node_modules folder contains external dependencies that cannot be included due to vite limitation.

Fix #296.

### CODE REVIEW

**Comment by benoitf** [comment]
I think you're missing this file
https://github.com/containers/podman-desktop/blob/main/.npmrc

So node_modules is not symlinks

**Comment by dgolovin** [comment]
@odockal would you please look at e2e test issues, i have issues to run them locally too with the same problem.

**Comment by odockal** [comment]
@dgolovin So the problem is that package manager (pnpm) does not update the devDevendencies to the `next` tagged version of `@podman-desktop/tests-playwright` and so it does not know latest changes and it cannot be compiled. I am working on fix.

**Comment by dgolovin** [comment]
> @dgolovin So the problem is that package manager (pnpm) does not update the devDevendencies to the `next` tagged version of `@podman-desktop/tests-playwright` and so it does not know latest changes and it cannot be compiled. I am working on fix.

Suspected that too, was going to look to `pnpm link` instead.

**Comment by odockal** [comment]
@dgolovin I got it working it seems: https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/291.

**Comment by dgolovin** [comment]
@odockal see also #292

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
