### PR TITLE
README: update image

### PR DESCRIPTION
**Pull request by vrothberg**
Update the reference to latest available alpha image.  Also make sure to add line before the screenshots to make sure text isn't rendered around it.

### CODE REVIEW

**Comment by vrothberg** [comment]
@benoitf PTAL

**Review by benoitf — APPROVED** [review]
I don't know if you can add a rolling tag like `preview` `nightly` etc that is coming from each commit


side note: we could also now update images to point to main branch as well

**Comment by vrothberg** [comment]
> I don't know if you can add a rolling tag like `preview` `nightly` etc that is coming from each commit

That would be nice to have.  Would the extension be updated automatically by Podman Desktop?

> side note: we could also now update images to point to main branch as well

Thanks for spotting! Done ✅

**Comment by benoitf** [comment]
> That would be nice to have. Would the extension be updated automatically by Podman Desktop?

no, for now extensions are only updated if their version in the catalog is updated
https://github.com/containers/podman-desktop-catalog/tree/gh-pages/api/extensions/redhat/redhat-authentication

the entry point is the catalog, not the OCI image location

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@vrothberg do you have rights to merge ?

**Comment by vrothberg** [comment]
merged :)

**Pull request merged**
